# Elasticsearch Configuration
ENV=${ENV}

STACK_VERSION=${STACK_VERSION}
CLUSTER_NAME=${CLUSTER_NAME}
MEM_LIMIT=${MEM_LIMIT}
SEED_HOSTS=${SEED_HOSTS}
SSL_VERIFY_MODE=${SSL_VERIFY_MODE}
LICENSE=${LICENSE}

ES_PORT=${ES_PORT}
ES_HOSTNAME=${ES_HOSTNAME}
ES_USERNAME=${ES_USERNAME}
ES_PASSWORD=${ES_PASSWORD}
ES_CERTIF=${ES_CERTIF}

# Host System Configuration
HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}
ES_HOST_VOLUME=${ES_HOST_VOLUME}

# NGINX Configuration
NGINX_CONFIG=${NGINX_CONFIG}
