default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer

  - repo: local
    hooks:
    # NOTE: This is a total unnecessary check, just used as part of the
    #       template. Remove this after creating the template.
    - id: check-python
      name: check-python
      entry: python --version
      language: system
      pass_filenames: no

    - id: black
      name: black
      entry: black
      language: system
      pass_filenames: true
      types:
        - python

    - id: ruff
      name: ruff
      entry: ruff --fix
      language: system
      pass_filenames: true
      files: "./"
      types:
        - python

    - id: mypy
      name: mypy
      entry: mypy
      language: system
      files: "src/rxiv_rest_api"
      pass_filenames: true
      types:
        - python

    - id: shellcheck
      name: shellcheck
      entry: shellcheck
      language: system
      types_or:
        - sh
        - shell
        - ash
        - bash
        - bats
        - dash
        - ksh

    - id: bandit
      name: bandit
      entry: bandit
      language: system
      args: ['--configfile', 'pyproject.toml', '-iii', '-lll']
      pass_filenames: true
      types:
        - python

    - id: vulture
      name: vulture
      entry: vulture
      language: system
      files: "src/rxiv_rest_api"
      description: Find unused Python code.
      pass_filenames: true
      types:
        - python

    - id: mccabe
      name: mccabe
      entry: python -m mccabe --min 10
      language: system
      files: "src/rxiv_rest_api"
      pass_filenames: true
      types:
        - python
