exclude: "^docs/|/migrations/|devcontainer.json"
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: local
    hooks:

    - id: ruff-format
      name: ruff-format
      entry: ruff format --no-force-exclude
      language: system
      pass_filenames: true
      types:
        - python

    - id: ruff-linter
      name: ruff-linter
      entry: ruff check
      language: system
      exclude: "docs/|migrations/"
      pass_filenames: true
      types:
        - python

    - id: bandit
      name: bandit
      entry: bandit
      language: system
      args: ['--configfile', 'pyproject.toml', '-iii', '-lll']
      pass_filenames: true
      types:
        - python

    - id: mypy
      name: mypy
      entry: mypy .
      language: system
      pass_filenames: false
