backend: compose
env-file: .env
defaults:
  profile: ${{ env.SUGAR_ENV or env.ENV }}
  project-name: literev-es

profiles:
  prod:
    config-path:
      # - containers/compose.nginx.yaml
      - containers/compose.elasticsearch.yaml
    env-file: .env
    services:
      default:
        - es01-ssl
        # - nginx
        # - certbot
      available:
        - name: es01-ssl
        # - name: nginx
        # - name: certbot
  dev:
    config-path:
      - containers/compose.elasticsearch.dev.yaml
    env-file: .env
    services:
      default:
       - es
      available:
        - name: es
  staging:
    config-path:
      - containers/compose.elasticsearch.staging.yaml
    env-file: .env
    services:
      default:
        - es
      available:
        - name: es

  nginx-prod:
    config-path:
      - containers/compose.nginx.yaml
      # - containers/compose.elasticsearch.yaml
    env-file: .env
    services:
      default:
        - nginx
        - certbot
      available:
        - name: nginx
        - name: certbot