version: 1.0
compose-app: docker compose
# env-file: .env
defaults:
  group: prod
  project-name: rxiv-rest
groups:
  prod:
    compose-path:
      - containers/compose.nginx.yaml
      - containers/compose.elasticsearch.yaml
    env-file: ./.env
    services:
      default: es01,nginx,certbot
      available:
        - name: es01
        - name: nginx
        - name: certbot
  dev:
    compose-path:
      - containers/compose.elasticsearch.dev.yaml
    env-file: ./.env
    services:
      default: es
      available:
        - name: es
