backend: compose
env-file: .envs/.env
defaults:
  profile: ${{ env.SUGAR_ENV or env.ENV }}
  project-name: literev-es

profiles:
  prod:
    config-path:
      - containers/compose.elasticsearch.yaml
    env-file: .envs/.env
    services:
      default:
        - es
      available:
        - name: es

  dev:
    config-path:
      - containers/compose.elasticsearch.dev.yaml
    env-file: .envs/.env
    services:
      default:
       - es01-dev
      available:
        - name: es01-dev

  staging:
    config-path:
      - containers/compose.elasticsearch.staging.yaml
    env-file: .envs/.env
    services:
      default:
        - es
      available:
        - name: es

  nginx-prod:
    config-path:
      - containers/compose.nginx.yaml
    env-file: .envs/.env
    services:
      default:
        - nginx
        - certbot
      available:
        - name: nginx
        - name: certbot
