# Elasticsearch Configuration
STACK_VERSION=${STACK_VERSION}
CLUSTER_NAME=${CLUSTER_NAME}
LICENSE=${LICENSE}
ES_PORT=${ES_PORT}
MEM_LIMIT=${MEM_LIMIT}
ES_HOST=${ES_HOST}
ES_USERNAME=${ES_USERNAME}
ES_PASSWORD=${ES_PASSWORD}

# Host System Configuration
HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}

# NGINX Configuration
NGINX_CONFIG=${NGINX_CONFIG}
