services:
  nginx:
    build:
      context: ".."
      dockerfile: "containers/dockerfile.nginx" # Relative path
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    env_file:
      - ../.env
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONFIG}:/etc/nginx # Relative path
      - ${NGINX_CONFIG}/certbot/conf:/etc/nginx/letsencrypt
    networks:
      - elastic

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ${NGINX_CONFIG}/certbot/conf:/etc/letsencrypt
      - ${NGINX_CONFIG}/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - elastic

networks:
  elastic:
