services:
  es-dev:
    hostname: es-dev
    container_name: es-dev
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    user: "1000:1000"  # Set the UID:GID to run the container
    env_file:
      ../.env
    environment:
      - discovery.type=single-node
      - node.name=es-dev
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k ${ES_HOSTNAME} | grep -q 'missing authentication credentials'"]
