version: "3.9"

services:
  es01:
    profiles: ["ssl"]
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es01
    env_file: ../.envs/.env
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/live/es.literev.com/fullchain.pem
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/live/es.literev.com/privkey.pem
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/live/es.literev.com/chain.pem
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/live/es.literev.com/fullchain.pem
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/live/es.literev.com/privkey.pem
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/live/es.literev.com/chain.pem
      - path.repo=/usr/share/elasticsearch/snapshots
      - ELASTIC_PASSWORD=${ES_PASSWORD}
    volumes:
      - certbot_conf:/usr/share/elasticsearch/config/certs:ro
      - esdata1:/usr/share/elasticsearch/data
      - es_snapshots:/usr/share/elasticsearch/snapshots
    ports:
      - "${ES_PORT}:9200"
    networks: [elastic]
    healthcheck:
      test: ["CMD-SHELL", "curl -kfSs -u elastic:${ES_PASSWORD} https://es01:9200/_cluster/health || exit 1"]


volumes:
  esdata1:
    driver: local
    name: es_legal_data_1
  certbot_conf:
    name: certbot_conf
  certbot_www:
    name: certbot_www
  es_snapshots:
    name: es_snapshots


networks:
  elastic:
