services:
  es01-dev:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - esdata_dev:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT}:9200"
    env_file:
      - ../.envs/.env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=${ES_PASSWORD}
    mem_limit: ${MEM_LIMIT:-4g}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u elastic:${ES_PASSWORD} http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - literev

networks:
  literev:
    driver: bridge

volumes:
  esdata_dev:
