version: "3.9"

services:
  es:
    hostname: es
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    user: "1000:1000"  # Set the UID:GID to run the container
    environment:
      - discovery.type=single-node
      - node.name=es
      - ELASTIC_PASSWORD=worksfine
      - bootstrap.memory_lock=true
    ports:
      - 9200:9200
    expose:
      - 9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k https://localhost:9200 | grep -q 'missing authentication credentials'"]
