services:
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    user: "1000:1000" # Set the UID:GID to run the container
    env_file:
      - ../.env
    environment:
      - discovery.type=single-node
      - node.name=es
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g  # Ensure proper memory allocation
      - bootstrap.memory_lock=true
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
    volumes:
      - type: bind
        source: ../containers/init-scripts
        target: /usr/share/elasticsearch/init-scripts
        read_only: true
      - type: bind
        source: ${ES_HOST_VOLUME}
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 20s
    networks:
      - literev_literev

networks:
  literev_literev:
    external: true
