# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
- name: 🙋  Usage Questions
  url: https://github.com/xmnlab/rxiv-restapi.git/discussions
  about: |
    Use rXiv REST API's GitHub Discussions to ask "How do I do X with rXiv REST API?".
- name: 📖  Tutorial
  url: https://github.com/xmnlab/rxiv-restapi.git
  about: |
    The rXiv REST API tutorial is continually updated and provides an in depth walkthrough
    of how to use the latest release of rXiv REST API.
- name: 📝  rXiv REST API Code of Conduct
  url: https://github.com/xmnlab/rxiv-restapi.git/coc/CODE_OF_CONDUCT.md
  about: Expectations for how people will interact with each other on rXiv REST API's GitHub.
