name: es-journals
channels:
  - nodefaults
  - conda-forge
dependencies:
  - elasticsearch
  - loguru
  - nodejs  # used by semantic-release
  - python >=3.8.1,<4
  - pip
  - poetry
  - r-medrxivr
  - r-base
  - shellcheck
  - typer
  - pip:
    - makim
    - containers-sugar
    - pytest
    - tqdm
  
