name: es-journals
channels:
  - nodefaults
  - conda-forge
dependencies:
  - elasticsearch
  - loguru
  - nodejs  # used by semantic-release
  - python >=3.8.1,<4
  - pip
  - poetry
  - r-medrxivr
  - r-base
  - shellcheck
  - typer
  - pip:
    - makim==1.15.2
    - containers-sugar==1.13.0
    - pytest
    - tqdm
