name: es-journals
channels:
  - nodefaults
  - conda-forge
dependencies:
  - elasticsearch
  - loguru
  - nodejs  # used by semantic-release
  - python >=3.8.1,<13.3
  - pip
  - poetry
  - r-base
  - r-devtools
  - shellcheck
  - typer
  - pip:
    - compose-go >=2.20.2,<2.31.0
    - makim==1.20.0
    - containers-sugar
    - pytest
    - tqdm
  
