name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Elasticsearch Configuration
  STACK_VERSION: 8.12.0
  CLUSTER_NAME: docker-cluster
  MEM_LIMIT: 1073741824
  LICENSE: basic
  #
  ES_PORT: 9200
  ES_HOSTNAME: https://localhost:9200
  ES_USERNAME: elastic
  ES_PASSWORD: worksfine
  ES_CERTIF: containers/esconfig/certs/http_ca.crt
  # Host System Configuration
  HOST_UID: 1000
  HOST_GID: 1000
  ES_HOST_VOLUME: /opt/services/data/elasticsearch/data

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/base.yaml
        channels: conda-forge,nodefaults
        channel-priority: true
        activate-environment: es-journals
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Set Environment Variable
      run: echo "GITHUB_PAT=${{ secrets.DEVTOOLS_PAT }}" >> $GITHUB_ENV

    - name: Setup development environment for Rxivs
      run: |
        for rxiv_name in biorxiv medrxiv; do
            makim develop.setup-dev-env --index-name $rxiv_name
        done

    - name: Start Elasticsearch
      run: |
        sugar ext start --group dev --options -d

    # - name: Copy and test certificates
    #   run: bash .github/ci/healthcheck.sh es 80 && makim develop.test-certs

    - name: Fetch and process MedRxiv data
      run: |       
        bash scripts/fetch_rxivx_data.sh medrxiv

    - name: Count documents in MedRxiv index
      run: |       
        makim develop.count-docs-in-index --index-name medrxiv
