name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Elasticsearch Configuration
  STACK_VERSION: 8.17.2
  CLUSTER_NAME: docker-cluster
  MEM_LIMIT: 4g
  LICENSE: basic
  SSL_VERIFY_MODE: certificate
  #
  ES_PORT: 9200
  ES_HOSTNAME: https://localhost:9200
  ES_USERNAME: elastic
  ES_PASSWORD: worksfine
  ES_CERTIF: containers/esconfig/certs/http_ca.crt
  # Host System Configuration
  HOST_UID: 1000
  HOST_GID: 1000
  ES_HOST_VOLUME: /opt/services/data/elasticsearch/data

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - uses: mamba-org/setup-micromamba@v1
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/base.yaml
        channels: conda-forge,nodefaults
        channel-priority: true
        activate-environment: es-journals
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Set Environment Variable
      run: echo "GITHUB_PAT=${{ secrets.DEVTOOLS_PAT }}" >> $GITHUB_ENV

    - name: Check if poetry.lock is updated
      run: poetry check

    - name: Install dependencies
      run: poetry install --no-root

    - name: Clean-up
      run: makim clean.tmp

    - name: Setup development environment for Rxivs
      run: |
        for rxiv_name in biorxiv medrxiv; do
            makim develop.setup-dev-env --index-name $rxiv_name
        done

    - name: Start Elasticsearch
      run: |
        sugar compose ext start --group dev --options -d

    - name: Fetch and process MedRxiv data
      run: |
        bash scripts/fetch_rxivx_data.sh medrxiv

    - name: Count documents in MedRxiv index
      run: |
        makim develop.count-docs-in-index --index-name medrxiv

    - name: Count documents in MedRxiv index
      run: |
        makim tests --index-name medrxiv

    - name: Run tests
      run: makim tests.unittest
